### ISSUE TITLE
magento 1.9.3 synchronisation problem

### ISSUE THREAD

**Issue by tomwic** [OCA/connector-magento#239]
after update magento to v1.9.3 I have problem with importing:
- magento sales orders:
  /connector-magento-8.0/magentoerpconnect/sale.py", line 647, in _clean_magento_items
     if item.get('parent_item_id'):
  AttributeError: 'str' object has no attribute 'get'
- magento product categories:
  /connector-magento-8.0/magentoerpconnect/product_category.py", line 130, in filter_ids
  if tree['children']:
  TypeError: string indices must be integers, not str

Could you please help?

**Comment by tomwic** [comment]
Its magento problem, temparary fix is here: http://magento.stackexchange.com/questions/140761/soap-connection-problems-after-1-9-3-0-update

....expecting permanent fix the problem in v1.9.3.1
